[workspace]
resolver = "2"
members = ["engine", "sandbox"]

[workspace.dependencies]
anyhow = "1.0.77"
atomic_float = "0.1.0"
glium = "0.33.0"
glutin = "0.30.4"
glutin-winit = "0.3"
nalgebra = "0.32.3"
rand = "0.8.5"
raw-window-handle = "0.5"
winit = "0.28"
algurulgar = { path = "engine" }
